
export const GET_DATA_LOADING_HOME = 'GET_DATA_LODING_HOME';
export const GET_DATA_SUCCESS_UPPER = 'GET_DATA_SUCCESS_UPPER';
export const GET_DATA_SUCCESS_LOWER = 'GET_DATA_SUCCESS_LOWER';
export const GET_DATA_ERROR_HOME = 'GET_DATA_ERROR_HOME';